// Guided curriculum. Each lesson = a progression + a constraint (focus) + coaching.
// focus: roots | chord | guide | thirds | blues | pentatonic | scale — decides which
// notes are highlighted as targets and what the mic scores as a "hit".
// demo: Demo kinds (js/demo.js) the sax plays on "Hear demo", one per loop, cycling.
// Optional: callResponse (bool), swing ('0.5' straight … '0.68' hard swing).
// Keep lessons of the same level together: the sidebar groups consecutive levels.
window.LESSONS = [
  // ---------- Foundations ----------
  {
    id: 'long-tones',
    title: 'Long tones on chord tones',
    level: 'Foundations',
    progression: 'dorian-vamp', key: 'D', tempo: 70, focus: 'chord',
    demo: ['long-tones'],
    goal: 'Warm up your sound and tuning while hearing how each chord tone sits against the band.',
    steps: [
      'Play the root as a whole note (4 beats) with a full, steady tone. Watch the tuning needle.',
      'Do the same on the ♭3, the 5 and the ♭7. Notice how each one gives a different colour.',
      'Crescendo through each note: start soft, swell to loud, return to soft.',
      'Play each chord tone in both octaves (check the fingering diagrams for the upper one).',
    ],
    tip: 'Good tone is part of improvising. A simple idea with a great sound beats a clever one with a thin sound.',
  },
  {
    id: 'roots',
    title: 'Hear the changes: roots only',
    level: 'Foundations',
    progression: 'ii-V-I', key: 'Bb', tempo: 80, focus: 'roots',
    demo: ['root-whole', 'root-quarters', 'root-rhythm'],
    goal: 'Feel where each chord changes by playing only its root.',
    steps: [
      'Press Play and listen to one full loop without playing. Hum the bass on beat 1 of each bar.',
      'Play the root of each chord on beat 1 and hold it through the bar.',
      'Now play the root on all four beats — long, even quarter notes, like a bassist.',
      'Finally, play the root with any rhythm you like. Only the rhythm changes, never the note.',
    ],
    tip: 'If the target % on the mic panel stays above 80%, move on.',
  },
  {
    id: 'arpeggios',
    title: 'Arpeggios: 1 – 3 – 5 – 7',
    level: 'Foundations',
    progression: 'ii-V-I', key: 'Bb', tempo: 80, focus: 'chord',
    demo: ['arp-up', 'arp-down', 'arp-3'],
    goal: 'Know the four chord tones of each chord without thinking.',
    steps: [
      'Play each arpeggio up (R 3 5 7) in quarter notes, one chord per bar.',
      'Play it down (7 5 3 R). Then alternate up for one chord, down for the next.',
      'Start from the 3rd instead of the root: 3 5 7 R.',
      'Improvise using only chord tones, in any order and rhythm.',
    ],
    tip: 'Chord tones are the "safe" notes — every other note is a passing note between them.',
  },
  {
    id: 'digital-patterns',
    title: 'Digital patterns: 1-2-3-5',
    level: 'Foundations',
    progression: 'ii-V-I', key: 'Bb', tempo: 90, focus: 'chord',
    demo: ['digital'],
    goal: 'Learn a classic four-note cell that outlines any chord and fits over fast changes.',
    steps: [
      'On each chord, play scale degrees 1-2-3-5 as quarter notes (e.g. over Cmaj7: C D E G).',
      'Reverse it: 5-3-2-1. Then alternate: up on one chord, down on the next.',
      'Play it as eighth notes, twice per bar.',
      'Start the pattern from the 3rd (3-5-7-9) for a more modern sound.',
    ],
    tip: 'Coltrane used 1-2-3-5 cells to get through Giant Steps. Small patterns, big mileage.',
  },
  {
    id: 'guide-tones',
    title: 'Guide tones: 3rds and 7ths',
    level: 'Foundations',
    progression: 'ii-V-I', key: 'Bb', tempo: 90, focus: 'guide',
    demo: ['guide'],
    goal: 'Outline the harmony with just two notes per chord and smooth voice leading.',
    steps: [
      'Play only the 3rd of each chord as a whole note.',
      'Play only the 7th of each chord.',
      'Connect them: the 7th of the ii chord moves down a half step to the 3rd of V. The 7th of V moves down a half step to the 3rd of I.',
      'Improvise a half-note line that uses only 3rds and 7ths, always moving to the nearest one.',
    ],
    tip: 'These half-step resolutions are what make a line sound like it "knows the changes".',
  },
  {
    id: 'approach-notes',
    title: 'Chromatic approach notes',
    level: 'Foundations',
    progression: 'ii-V-I', key: 'Bb', tempo: 90, focus: 'chord',
    demo: ['approach'],
    goal: 'Use "wrong" notes on purpose: a half step below a chord tone, resolving up into it.',
    steps: [
      'Pick a chord tone. Play the note a half step below it on the "and" of a beat, then the chord tone on the next beat.',
      'Approach every chord tone of the arpeggio from below: e.g. B–C, D♯–E, F♯–G over Cmaj7.',
      'Now approach from a scale step above instead.',
      'Improvise, but slip one chromatic approach into every bar.',
    ],
    tip: 'The outside % on the mic panel will go up — that is fine, as long as each outside note resolves.',
  },

  // ---------- Blues ----------
  {
    id: 'blues-scale',
    title: 'The blues scale',
    level: 'Blues',
    progression: 'blues', key: 'Bb', tempo: 100, focus: 'blues',
    demo: ['riff'],
    goal: 'Get a whole 12-bar chorus of sound from one six-note scale.',
    steps: [
      'Play the blues scale up and down slowly over the form (click "Play scale" to hear it).',
      'Make 2-bar phrases, then rest 2 bars. Leave space!',
      'Lean on the ♭3 and bend it up toward the 3rd. Use the ♭5 only as a passing note.',
      'Repeat a short riff over the changing chords — the riff stays, the harmony moves under it.',
    ],
    tip: 'Great blues solos repeat ideas. Say something, then say it again.',
  },
  {
    id: 'minor-pentatonic',
    title: 'Minor pentatonic: five safe notes',
    level: 'Blues',
    progression: 'blues', key: 'Bb', tempo: 100, focus: 'pentatonic',
    demo: ['riff'],
    goal: 'Use the five-note minor pentatonic — the blues scale without the ♭5 — for strong, simple riffs.',
    steps: [
      'Play the minor pentatonic up and down. It is the blues scale minus the ♭5.',
      'Make riffs from three adjacent notes. Repeat each riff across bars 1–4.',
      'Play in two octaves: find the upper notes in the fingering diagrams.',
      'Mix in the ♭5 from the blues scale as a passing note between the 4 and the 5.',
    ],
    tip: 'No note of the minor pentatonic clashes badly with a blues — so put all your attention on rhythm and sound.',
  },
  {
    id: 'rhythm-first',
    title: 'Rhythm first: one-note solo',
    level: 'Blues',
    progression: 'dominant-vamp', key: 'Bb', tempo: 110, focus: 'roots',
    demo: ['root-rhythm'],
    goal: 'Improvise with rhythm alone. The groove matters more than the notes.',
    steps: [
      'Play one note, the root, and make up rhythms: short/long, on the beat/off the beat.',
      'Try accenting the off-beats ("and"s). Tongue lightly: "doo-DAH".',
      'Play a rhythm, rest for the same length, then repeat it.',
      'Allow yourself a second note (the ♭7) and keep the focus on rhythm.',
    ],
    tip: 'Record yourself: phrases that start on an off-beat almost always sound more swinging.',
  },
  {
    id: 'space-phrasing',
    title: 'Phrasing and space',
    level: 'Blues',
    progression: 'blues', key: 'Bb', tempo: 100, focus: 'blues',
    demo: ['space'],
    goal: 'Control phrase length and leave room to breathe — the band fills the gaps.',
    steps: [
      'Play 1-bar phrases, each followed by 1 bar of rest.',
      'Play 2-bar phrases with 2 bars of rest. Then 4-bar phrases with 4 bars of rest.',
      'Start your phrases in different places: beat 1, beat 2, the "and" of 4 before the bar.',
      'Take a full chorus and rest at least half of it.',
    ],
    tip: 'Miles Davis: "It\'s not the notes you play, it\'s the notes you don\'t play."',
  },
  {
    id: 'blues-chord-tones',
    title: 'Blues with chord tones',
    level: 'Blues',
    progression: 'blues', key: 'Bb', tempo: 110, focus: 'chord',
    demo: ['arp-up', 'riff'],
    goal: 'Mix the blues scale with the real chord tones so you follow the changes.',
    steps: [
      'Play the arpeggio of each chord in the blues. Notice the 3rd changes between I7 and IV7.',
      'In bar 5 (the IV chord), target its 3rd. It is the ♭7 of the I chord moved down a half step.',
      'Alternate: 2 bars of blues-scale riffs, 2 bars of chord tones.',
    ],
    tip: 'The major 3rd of I7 against the ♭3 from the blues scale is the classic blues tension.',
  },
  {
    id: 'minor-blues',
    title: 'Minor blues',
    level: 'Blues',
    progression: 'minor-blues', key: 'C', tempo: 110, focus: 'blues',
    demo: ['riff', 'arp-up'],
    goal: 'Handle a darker blues: minor chords, and a ♭VI7–V7 turnaround at the end.',
    steps: [
      'Play the blues scale over the whole form. It fits even better than on a major blues.',
      'In bars 9–10 (the ♭VI7 and V7♭9), switch Highlight to "Chord tones" and find the 3rd of each.',
      'Land on the root of the i chord in bar 11 and hold it.',
      'Improvise two choruses, building intensity in the second one.',
    ],
    tip: 'The ♭VI7 → V7 in bars 9–10 is the most colourful moment of the form. Play the chord tones there.',
  },

  // ---------- Ear training ----------
  {
    id: 'call-response',
    title: 'Call & response: blues',
    level: 'Ear training',
    progression: 'blues', key: 'Bb', tempo: 90, focus: 'chord', callResponse: true,
    demo: ['echo'],
    goal: 'Train your ear to hear and repeat phrases, the way players trade ideas.',
    steps: [
      'The band plays a short phrase for 2 bars (LISTEN). Then you have 2 bars (YOUR TURN).',
      'First echo only the rhythm on any note.',
      'Then try to echo the exact notes. Use "Show notes" if you get stuck.',
      'Advanced: answer the phrase instead of copying it — same rhythm, different notes.',
    ],
    tip: 'Sing the phrase back first. If you can sing it, you can play it.',
  },
  {
    id: 'call-response-changes',
    title: 'Call & response: ii–V–I',
    level: 'Ear training',
    progression: 'ii-V-I', key: 'Bb', tempo: 90, focus: 'chord', callResponse: true,
    demo: ['echo'],
    goal: 'Echo phrases that move through chord changes, so your ear learns how lines follow harmony.',
    steps: [
      'Echo each phrase exactly. The phrases are built from chord tones on strong beats.',
      'Transpose the echo: play it back one octave higher or lower.',
      'Echo the phrase, but end on a different chord tone.',
      'Answer with a phrase of your own that resolves to the 3rd of the I chord.',
    ],
    tip: 'Hearing the difference between a phrase over ii and the same notes over V is ear training for changes.',
  },

  // ---------- Modal ----------
  {
    id: 'dorian-motifs',
    title: 'Modal: Dorian motifs',
    level: 'Modal',
    progression: 'dorian-vamp', key: 'D', tempo: 130, focus: 'scale',
    demo: ['motif'],
    goal: 'Build a solo from one small idea over a single chord.',
    steps: [
      'Play the Dorian scale up and down. The natural 6th is its characteristic note.',
      'Invent a 3-note motif. Play it, then move it up one scale step and play it again.',
      'Change only its rhythm, then only its last note.',
      'Play in 4ths (for example R–4, 2–5, ♭3–♭7) for a modern modal sound.',
    ],
    tip: 'Over one chord there are no changes to miss. All the interest comes from how you develop ideas.',
  },
  {
    id: 'mixolydian-vamp',
    title: 'Mixolydian funk vamp',
    level: 'Modal',
    progression: 'dominant-vamp', key: 'Bb', tempo: 100, focus: 'scale', swing: '0.5',
    demo: ['funk'],
    goal: 'Play straight-eighth, funky lines over a dominant chord using Mixolydian.',
    steps: [
      'Play Mixolydian up and down in straight eighths. It is a major scale with a ♭7.',
      'Make short, punchy two-note figures between the 3 and the ♭7 (the tritone).',
      'Use lots of repeated notes and ghosted (very soft) notes for a funk feel.',
      'Mix in the minor pentatonic for a bluesier sound: switch Highlight to "Pentatonic".',
    ],
    tip: 'In funk, short notes and precise rests make the groove. Think like a drummer.',
  },
  {
    id: 'displacement',
    title: 'Rhythmic displacement',
    level: 'Modal',
    progression: 'dorian-vamp', key: 'D', tempo: 110, focus: 'scale',
    demo: ['displace'],
    goal: 'Take one phrase and move it around the bar. The same notes feel completely different.',
    steps: [
      'Make up a 4-note phrase in eighth notes that starts on beat 1. Play it every bar.',
      'Start the same phrase one eighth note later (on the "and" of 1).',
      'Keep shifting it by an eighth note until it starts on the "and" of 4.',
      'Improvise freely, but keep returning to your phrase in a new rhythmic position.',
    ],
    tip: 'Phrases that start on off-beats create forward motion. That is much of what "swing" really is.',
  },

  // ---------- Changes ----------
  {
    id: 'target-thirds',
    title: 'Target notes: land on the 3rd',
    level: 'Changes',
    progression: 'autumn-cycle', key: 'Bb', tempo: 100, focus: 'thirds',
    demo: ['target'],
    goal: 'Aim each phrase so it lands on the 3rd of the new chord on beat 1.',
    steps: [
      'Play just the 3rd of every chord on beat 1. Watch the "next" chord to prepare.',
      'Approach each 3rd from a half step below (on the "and" of 4).',
      'Improvise freely, but hit the 3rd on beat 1 of each chord change.',
    ],
    tip: 'Target, then fill. Know where you are landing before you know how you get there.',
  },
  {
    id: 'enclosures',
    title: 'Enclosures',
    level: 'Changes',
    progression: 'autumn-cycle', key: 'Bb', tempo: 90, focus: 'thirds',
    demo: ['enclose'],
    goal: 'Surround a target note from above and below before landing on it — the bebop sound.',
    steps: [
      'Enclose the 3rd of each chord: scale note above, half step below, then the 3rd on the beat.',
      'Try the reverse: half step below, scale note above, target.',
      'Use a 4-note enclosure: above, below (chromatic), below (scale), target.',
      'Improvise and enclose the target at every chord change.',
    ],
    tip: 'Charlie Parker used enclosures constantly. They make your target land with authority.',
  },
  {
    id: 'turnaround-guide',
    title: 'Turnarounds: I–vi–ii–V',
    level: 'Changes',
    progression: 'turnaround', key: 'F', tempo: 110, focus: 'guide',
    demo: ['guide'],
    goal: 'Navigate a fast-moving, one-chord-per-bar progression with guide tones.',
    steps: [
      'Play a guide-tone line: 3rd or 7th of each chord, moving to the nearest one each bar.',
      'Add one passing note between each guide tone (quarter notes: guide, passing, guide, passing).',
      'Fill each bar with eighth notes that start on the guide tone.',
      'Increase the tempo in 10 bpm steps while keeping the guide tones on beat 1.',
    ],
    tip: 'This turnaround is the backbone of "Rhythm Changes" and countless standards. Learn it in several keys.',
  },
  {
    id: 'major-pentatonic',
    title: 'Major pentatonic over changes',
    level: 'Changes',
    progression: 'ii-V-I', key: 'Bb', tempo: 110, focus: 'pentatonic',
    demo: ['riff'],
    goal: 'One five-note shape fits the whole ii–V–I. It gives you an open, melodic sound.',
    steps: [
      'Play the major pentatonic of the key over the whole progression.',
      'Notice which pentatonic notes are chord tones on each chord. The Highlight shows them in teal.',
      'Play pentatonic phrases in 4ths and wide leaps rather than stepwise.',
      'Alternate: 2 bars of pentatonic, 2 bars of chord tones.',
    ],
    tip: 'Pentatonics over changes are a staple of modern players like Michael Brecker.',
  },
  {
    id: 'minor-ii-v',
    title: 'Minor ii–V–i',
    level: 'Changes',
    progression: 'minor-ii-V-i', key: 'C', tempo: 100, focus: 'chord',
    demo: ['arp-up', 'guide'],
    goal: 'Handle the half-diminished and altered dominant chords of a minor key.',
    steps: [
      'Arpeggiate each chord. On the m7♭5 chord, the ♭5 is the note to hear.',
      'On the V7♭9, find the ♭9: it resolves down a half step to the 5th of the i chord.',
      'Play guide tones through the progression, as in the guide-tones lesson.',
      'Improvise, resolving strongly on the i chord.',
    ],
    tip: 'Minor-key tension is sweeter when it resolves — hold your resolution note.',
  },
  {
    id: 'free-play',
    title: 'Put it together',
    level: 'Changes',
    progression: 'autumn-cycle', key: 'Bb', tempo: 120, focus: 'chord',
    demo: ['lick'],
    goal: 'Solo over the changes using everything so far.',
    steps: [
      'Take 2 choruses. Start sparse and low, and build intensity toward the end.',
      'Use a mix: guide tones, chord tones, target 3rds, enclosures and some rests.',
      'Aim for a chord-tone % around 50–70% — enough to sound "inside", with tension along the way.',
    ],
    tip: 'Tell a story: statement, development, climax, resolution.',
  },
];
